C        Generated by TAPENADE     (INRIA, Tropics team)
C  Tapenade 3.6 (r4343) - 10 Feb 2012 10:52
C
C  Differentiation of calc_norm in reverse (adjoint) mode:
C   gradient     of useful results: tmp_norm a
C   with respect to varying inputs: a
      SUBROUTINE CALC_NORM_BO(a, ab, b, norm_type, tmp_norm, tmp_normb)
      IMPLICIT NONE
      REAL a, b, tmp_norm
      REAL ab, tmp_normb
      INTEGER norm_type
C
      IF (norm_type .EQ. 2) THEN
        ab = ab + 2*(a-b)*tmp_normb
      ELSE
        STOP
      END IF
      END
