C        Generated by TAPENADE     (INRIA, Tropics team)
C  Tapenade 3.6 (r4343) - 10 Feb 2012 10:52
C
C  Differentiation of lim_vanleer in reverse (adjoint) mode:
C   gradient     of useful results: lim_vanleer
C   with respect to varying inputs: x y
C
C*************************************************************************
      SUBROUTINE LIM_VANLEER_BQ(x, xb, y, yb, lim_vanleerb)
      IMPLICIT NONE
C
C*************************************************************************
      REAL x, y
      REAL xb, yb
      REAL a, b
      REAL ab, bb
      REAL LIM_MINMOD
      REAL result1
      REAL result1b
      REAL lim_vanleerb
      REAL lim_vanleer
      a = 0.5*(x+y)
      result1 = LIM_MINMOD(x, y)
      b = 2.0*result1
C
      CALL LIM_MINMOD_BQ(a, ab, b, bb, lim_vanleerb)
      result1b = 2.0*bb
      CALL LIM_MINMOD_BQ(x, xb, y, yb, result1b)
      xb = xb + 0.5*ab
      yb = yb + 0.5*ab
      END
