C        Generated by TAPENADE     (INRIA, Tropics team)
C  Tapenade 3.6 (r4343) - 10 Feb 2012 10:52
C
C  Differentiation of objectivef in reverse (adjoint) mode:
C   gradient     of useful results: fmtip fsmach opt_obj
C   with respect to varying inputs: fmtip fsmach q opt_obj
C   RW status of diff variables: fmtip:incr fsmach:incr q:out opt_obj:in-zero
      SUBROUTINE OBJECTIVEF_BO(jd, kd, x, y, xv, yv, q, qb, xx, xy, yx, 
     +                         yy, opt_obj, opt_objb)
      USE PARAMS_GLOBAL
      USE PARAMS_SENSITIVITY
      IMPLICIT NONE
      INCLUDE 'DIFFSIZES.inc'
C  Hint: ISIZE1OFcoeffbINobjectivef should be the value of jd
      INTEGER jd, kd
      REAL q(jd, kd, nq), x(jd, kd), y(jd, kd), xv(jmax, kmax), yv(jmax
     +     , kmax)
      REAL qb(jd, kd, nq)
      REAL xx(jd, kd), xy(jd, kd)
      REAL yx(jd, kd), yy(jd, kd)
      REAL opt_obj
      REAL opt_objb
      REAL coeff(jd), tmp_norm
      REAL tmp_normb
      INTEGER j, k, np
      REAL coeffb(jd)
C
      IF (obj_ftype .EQ. obj_ftype_cp) THEN
        CALL CALC_CP(jd, kd, q, coeff)
C
        IF (obj_pointwise) THEN
          coeffb = 0.0
          coeffb(obj_points(1)) = coeffb(obj_points(1)) + opt_objb
        ELSE
          coeffb = 0.0
          DO np=obj_npoints,1,-1
            tmp_normb = opt_objb
            CALL CALC_NORM_BO(coeff(obj_points(np)), coeffb(obj_points(
     +                        np)), obj_f(obj_points(np)), obj_normtype
     +                        , tmp_norm, tmp_normb)
          ENDDO
        END IF
        CALL CALC_CP_BO(jd, kd, q, qb, coeff, coeffb)
        opt_objb = 0.0
      ELSE
        STOP
      END IF
      END
