C        Generated by TAPENADE     (INRIA, Tropics team)
C  Tapenade 3.6 (r4343) - 10 Feb 2012 10:52
C
C  Differentiation of turbc_inf in reverse (adjoint) mode:
C   gradient     of useful results: q
C   with respect to varying inputs: q
C
C*************************************************************
      SUBROUTINE TURBC_INF_BQ(q, qb, jd, kd, js, je, ks, ke, idir)
      USE PARAMS_GLOBAL
      IMPLICIT NONE
C*************************************************************
C*************************************************************
      INTEGER jd, kd
      REAL q(jd, kd, nq)
      REAL qb(jd, kd, nq)
      INTEGER js, je, ks, ke, idir
C
C.. local variables
C
      INTEGER j, k, j1, k1, iadd, iadir
      INTRINSIC SIGN
      INTRINSIC ABS
C
      IF (idir .GE. 0.) THEN
        iadir = idir
      ELSE
        iadir = -idir
      END IF
C
      IF (iadir .EQ. 1) THEN
        DO j=je,js,-1
          DO k=ke,ks,-1
            qb(j, k, nmv+1) = 0.0
          ENDDO
        ENDDO
      ELSE IF (iadir .EQ. 2) THEN
        DO k=ke,ks,-1
          DO j=je,js,-1
            qb(j, k, nmv+1) = 0.0
          ENDDO
        ENDDO
      END IF
      END
