C        Generated by TAPENADE     (INRIA, Tropics team)
C  Tapenade 3.6 (r4343) - 10 Feb 2012 10:52
C
C  Differentiation of turbc_periodic in reverse (adjoint) mode:
C   gradient     of useful results: q
C   with respect to varying inputs: q
C
C*************************************************************
      SUBROUTINE TURBC_PERIODIC_BQ(q, qb, jd, kd, js, je, ks, ke, idir)
      USE PARAMS_GLOBAL
      IMPLICIT NONE
C*************************************************************
C*************************************************************
      INTEGER jd, kd
      REAL q(jd, kd, nq)
      REAL qb(jd, kd, nq)
      INTEGER js, je, ks, ke, idir
C
C.. local variables
C
      INTEGER j, k, jc, jj, jj1, kc, kk, kk1, iadd, iadir
C
      REAL tmp
      REAL tmp0
      REAL tmp1
      REAL tmp2
      REAL tmpb
      INTRINSIC SIGN
      REAL tmp0b
      INTRINSIC ABS
      REAL tmp2b
      REAL tmp1b
C
      IF (idir .EQ. 1) THEN
        jj = je - js + 1
        DO j=js,je
          jj1 = j - js + 1
          CALL PUSHINTEGER4(jc)
          jc = jd - 2*jj + jj1
        ENDDO
        DO j=je,js,-1
          DO k=ke,ks,-1
            tmp2b = qb(j, k, nmv+1)
            qb(j, k, nmv+1) = 0.0
            qb(jc, k, nmv+1) = qb(jc, k, nmv+1) + tmp2b
          ENDDO
          CALL POPINTEGER4(jc)
        ENDDO
      ELSE IF (idir .EQ. -1) THEN
C
        jj = je - js + 1
        DO j=js,je
          jj1 = je - j + 1
          CALL PUSHINTEGER4(jc)
          jc = 1 + 2*jj - jj1
        ENDDO
        DO j=je,js,-1
          DO k=ke,ks,-1
            tmpb = qb(j, k, nmv+1)
            qb(j, k, nmv+1) = 0.0
            qb(jc, k, nmv+1) = qb(jc, k, nmv+1) + tmpb
          ENDDO
          CALL POPINTEGER4(jc)
        ENDDO
      ELSE IF (idir .EQ. 2) THEN
C
        kk = ke - ks + 1
        DO k=ks,ke
          kk1 = k - ks + 1
          CALL PUSHINTEGER4(kc)
          kc = kd - 2*kk + kk1
        ENDDO
        DO k=ke,ks,-1
          DO j=je,js,-1
            tmp0b = qb(j, k, nmv+1)
            qb(j, k, nmv+1) = 0.0
            qb(j, kc, nmv+1) = qb(j, kc, nmv+1) + tmp0b
          ENDDO
          CALL POPINTEGER4(kc)
        ENDDO
      ELSE IF (idir .EQ. -2) THEN
C
        kk = ke - ks + 1
        DO k=ks,ke
          kk1 = ke - k + 1
          CALL PUSHINTEGER4(kc)
          kc = 1 + 2*kk - kk1
        ENDDO
        DO k=ke,ks,-1
          DO j=je,js,-1
            tmp1b = qb(j, k, nmv+1)
            qb(j, k, nmv+1) = 0.0
            qb(j, kc, nmv+1) = qb(j, kc, nmv+1) + tmp1b
          ENDDO
          CALL POPINTEGER4(kc)
        ENDDO
      END IF
      END
