C        Generated by TAPENADE     (INRIA, Tropics team)
C  Tapenade 3.6 (r4343) - 10 Feb 2012 10:52
C
C  Differentiation of uv in reverse (adjoint) mode:
C   gradient     of useful results: uwall vwall
C   with respect to varying inputs: u v
C
C***********************************************************************
      SUBROUTINE UV_BQ(js, je, k, xx, xy, yx, yy, u, ub, v, vb, uwall, 
     +                 uwallb, vwall, vwallb, jd, kd)
      USE PARAMS_GLOBAL
      IMPLICIT NONE
C
C  solve for the cartesian momemtum components (ru,rv) from
C  the contravariant velocity components (u,v) along lines of j.
C     
C  note: consistent with metfv     
C
C***********************************************************************
C***********************************************************************
      INTEGER jd, kd
      REAL xx(jd, kd), xy(jd, kd), yx(jd, kd), yy(jd, kd)
      REAL u(mdim), v(mdim)
      REAL ub(mdim), vb(mdim)
C local variables
      REAL uwall(mdim), vwall(mdim)
      REAL uwallb(mdim), vwallb(mdim)
      INTEGER js, je, k, j
      REAL t11, t12, t21, t22, vol
      ub = 0.0
      vb = 0.0
      DO j=je,js,-1
        t11 = yy(j, k)
        t12 = -xy(j, k)
        t21 = -yx(j, k)
        t22 = xx(j, k)
        vol = 1./(t22*t11-t12*t21)
        ub(j) = ub(j) + vol*t11*uwallb(j) + vol*t21*vwallb(j)
        vb(j) = vb(j) + vol*t12*uwallb(j) + vol*t22*vwallb(j)
        vwallb(j) = 0.0
        uwallb(j) = 0.0
      ENDDO
      END
