C        Generated by TAPENADE     (INRIA, Tropics team)
C  Tapenade 3.6 (r4343) - 10 Feb 2012 10:52
C
C  Differentiation of visrhs in reverse (adjoint) mode:
C   gradient     of useful results: rey q s turmu
C   with respect to varying inputs: rey q s turmu
C   RW status of diff variables: rey:incr q:incr s:in-out turmu:incr
C***********************************************************************
      SUBROUTINE VISRHS_BQ(turmu, turmub, q, qb, s, sb, xx, xy, yx, yy, 
     +                     ug, vg, tscale, iblank, jd, kd)
      USE PARAMS_GLOBAL
      USE PARAMS_SENSITIVITY
      IMPLICIT NONE
      INCLUDE 'DIFFSIZES.inc'
C  Hint: ISIZE1OFf2bINvisrhs should be the value of mdim
C  Hint: ISIZE1OFf3bINvisrhs should be the value of mdim
C  Hint: ISIZE1OFf4bINvisrhs should be the value of mdim
C  Hint: ISIZE1OFf2vbINvisrhs should be the value of mdim
C  Hint: ISIZE1OFf3vbINvisrhs should be the value of mdim
C  Hint: ISIZE1OFf4vbINvisrhs should be the value of mdim
C  Hint: ISIZE1OFubINvisrhs should be the value of mdim
C  Hint: ISIZE1OFvbINvisrhs should be the value of mdim
C  Hint: ISIZE1OFebINvisrhs should be the value of mdim
C  Hint: ISIZE1OFa1vbINvisrhs should be the value of mdim
C  Hint: ISIZE1OFa2vbINvisrhs should be the value of mdim
C  Hint: ISIZE1OFa4vbINvisrhs should be the value of mdim
C  Hint: ISIZE1OFa5vbINvisrhs should be the value of mdim
C  Hint: ISIZE1OFb1vbINvisrhs should be the value of mdim
C  Hint: ISIZE1OFb2vbINvisrhs should be the value of mdim
C  Hint: ISIZE1OFb4vbINvisrhs should be the value of mdim
C  Hint: ISIZE1OFb5vbINvisrhs should be the value of mdim
C  Hint: ISIZE1OFd1vbINvisrhs should be the value of mdim
C  Hint: ISIZE1OFd2vbINvisrhs should be the value of mdim
C  Hint: ISIZE1OFd4vbINvisrhs should be the value of mdim
C  Hint: ISIZE1OFd5vbINvisrhs should be the value of mdim
C  Hint: ISIZE1OFd7vbINvisrhs should be the value of mdim
C
C  compute the viscous rhs 
C
C***********************************************************************
C***********************************************************************
      INTEGER jd, kd
      REAL q(jd, kd, nq), s(jd, kd, nv), turmu(jd, kd), tscale(jd, kd)
      REAL qb(jd, kd, nq), sb(jd, kd, nv), turmub(jd, kd)
      REAL ug(jd, kd), vg(jd, kd)
      REAL xx(jd, kd), xy(jd, kd), yx(jd, kd), yy(jd, kd)
C local variables
      INTEGER iblank(jd, kd)
C
      REAL f2(mdim), f3(mdim), f4(mdim)
      REAL f2v(mdim), f3v(mdim), f4v(mdim), u(mdim), v(mdim), e(mdim)
      REAL a1v(mdim), a2v(mdim), a4v(mdim), a5v(mdim)
      REAL b1v(mdim), b2v(mdim), b4v(mdim), b5v(mdim), d1v(mdim)
      REAL d2v(mdim), d4v(mdim), d5v(mdim), d7v(mdim)
C
C
      REAL gkpr, prtr, dr, c2b, c2bp, t4, t5, t6, t7, t8
      REAL t4b, t5b, t6b, t7b, t8b
      INTEGER j, k, km1, k1, jm1, j1, je, ke
      REAL ra, tt, vmue, turm, vnu, gkap, rj, b1, b2, b5, b4
      REAL rab, ttb, vmueb, turmb, vnub, gkapb, rjb, b1b, b2b, b5b
      REAL du, dv, dei, rjm, rjp, d1, d2, d4, d5, d7
      REAL dub, dvb, deib, rjmb, rjpb, d1b, d2b, d4b, d5b, d7b
      REAL ujp1, ujm1, dvj
      REAL ujp1b, ujm1b, dvjb
      REAL ejm1, dej, rk, rkm, rkp, a1, a2, a4, a5
      REAL ejm1b, dejb, rkmb, rkpb, a1b, a2b, a5b
      REAL ukp1, ukm1, duk
      REAL ukp1b, ukm1b, dukb
      REAL vkp1, vkm1, dvk, ekp1, ekm1, dek
      REAL vkp1b, vkm1b, dvkb, ekp1b, ekm1b, dekb
      REAL dre, duj, vjp1, vjm1, ejp1
      REAL dreb, dujb, vjp1b, vjm1b, ejp1b
      INTEGER branch
      REAL temp3
      REAL temp2
      REAL temp1
      REAL temp0
      REAL temp7b
      REAL d5vb(mdim)
      REAL f2vb(mdim)
      REAL temp7b14
      REAL temp7b13
      REAL tempb2
      REAL temp7b12
      REAL tempb1
      REAL temp7b11
      REAL tempb0
      REAL temp7b9
      REAL temp7b10
      REAL temp7b8
      REAL temp7b7
      REAL temp7b6
      REAL temp7b5
      REAL temp7b4
      REAL a1vb(mdim)
      REAL temp7b3
      REAL temp3b
      REAL temp7b2
      REAL f2b(mdim)
      REAL temp7b1
      REAL temp7b0
      REAL temp2b0
      REAL temp6b
      REAL b1vb(mdim)
      REAL vb(mdim)
      REAL a4vb(mdim)
      REAL f3vb(mdim)
      REAL temp5b0
      REAL b4vb(mdim)
      REAL tempb
      REAL d1vb(mdim)
      REAL temp2b
      REAL temp3b9
      REAL a2vb(mdim)
      REAL temp3b8
      REAL temp5b
      REAL f4b(mdim)
      REAL temp3b7
      REAL temp3b6
      REAL temp3b5
      REAL eb(mdim)
      REAL temp3b4
      REAL d4vb(mdim)
      REAL temp3b3
      REAL temp3b2
      REAL temp3b1
      REAL ub(mdim)
      REAL temp3b0
      REAL b2vb(mdim)
      REAL temp3b18
      REAL temp3b17
      REAL temp3b16
      REAL temp3b15
      REAL temp3b14
      REAL temp3b13
      REAL a5vb(mdim)
      REAL temp3b12
      REAL temp3b11
      REAL temp3b10
      REAL d7vb(mdim)
      REAL f4vb(mdim)
      REAL temp1b
      INTRINSIC SQRT
      REAL temp
      REAL temp6b0
      REAL b5vb(mdim)
      REAL d2vb(mdim)
      REAL temp1b0
      REAL temp6
      REAL f3b(mdim)
      REAL temp5
      REAL temp4
C
C*** first executable statement
C
      gkpr = gamma/pr
      prtr = pr/0.9
      dre = .5/rey
      c2b = 198.6/tinf
      c2bp = c2b + 1.
C
      eb = 0.0
      f2b = 0.0
      f3b = 0.0
      f4b = 0.0
      ub = 0.0
      vb = 0.0
      f3vb = 0.0
      d7vb = 0.0
      d4vb = 0.0
      dreb = 0.0
      d1vb = 0.0
      a4vb = 0.0
      f4vb = 0.0
      a1vb = 0.0
      d5vb = 0.0
      d2vb = 0.0
      a5vb = 0.0
      a2vb = 0.0
      f2vb = 0.0
      DO k=kbeg,kend
        DO j=1,jd
          ra = 1./q(j, k, 1)
          u(j) = q(j, k, 2)*ra
          v(j) = q(j, k, 3)*ra
          e(j) = q(j, k, 4)*ra - .5*(u(j)**2+v(j)**2)
          tt = ggm1*e(j)
          vmue = c2bp*tt*SQRT(tt)/(c2b+tt)
          turm = turmu(j, k)
          vnu = vmue + turm
          gkap = vmue + prtr*turm
          rj = 1./q(j, k, nq)
          rkm = 1./q(j, k-1, nq)
          rkp = 1./q(j, k+1, nq)
C
          a4v(j) = (xx(j, k)**2+xy(j, k)**2)*rj
          a1v(j) = (a4v(j)+xx(j, k)**2/3.*rj)*vnu*dre
          a2v(j) = (a4v(j)+xy(j, k)**2/3.*rj)*vnu*dre
          a5v(j) = xx(j, k)*xy(j, k)/3.*rj*vnu*dre
          a4v(j) = a4v(j)*gkpr*gkap*dre
C
          d1v(j) = (4./3.*xx(j, k-1)*yx(j, k-1)+xy(j, k-1)*yy(j, k-1))*
     +      rkm
          d1v(j) = d1v(j) + (4./3.*xx(j, k+1)*yx(j, k+1)+xy(j, k+1)*yy(j
     +      , k+1))*rkp
          d1v(j) = vnu*dre*d1v(j)
C
          d2v(j) = (4./3.*xy(j, k-1)*yy(j, k-1)+xx(j, k-1)*yx(j, k-1))*
     +      rkm
          d2v(j) = d2v(j) + (4./3.*xy(j, k+1)*yy(j, k+1)+xx(j, k+1)*yx(j
     +      , k+1))*rkp
          d2v(j) = vnu*dre*d2v(j)
C
          d4v(j) = (xy(j, k-1)*yy(j, k-1)+xx(j, k-1)*yx(j, k-1))*rkm
          d4v(j) = d4v(j) + (xy(j, k+1)*yy(j, k+1)+xx(j, k+1)*yx(j, k+1)
     +      )*rkp
          d4v(j) = d4v(j)*gkpr*gkap*dre
C
          d5v(j) = (-(2./3.*xy(j, k-1)*yx(j, k-1))+xx(j, k-1)*yy(j, k-1)
     +      )*rkm
          d5v(j) = d5v(j) + (-(2./3.*xy(j, k+1)*yx(j, k+1))+xx(j, k+1)*
     +      yy(j, k+1))*rkp
          d5v(j) = vnu*dre*d5v(j)
C
          d7v(j) = (-(2./3.*xx(j, k-1)*yy(j, k-1))+xy(j, k-1)*yx(j, k-1)
     +      )*rkm
          d7v(j) = d7v(j) + (-(2./3.*xx(j, k+1)*yy(j, k+1))+xy(j, k+1)*
     +      yx(j, k+1))*rkp
          d7v(j) = vnu*dre*d7v(j)
        ENDDO
C
        IF (nhalo .EQ. 1) THEN
          je = jend - 1
C
C
          CALL PUSHCONTROL1B(1)
        ELSE
          CALL PUSHCONTROL1B(0)
          IF (nhalo .GT. 1) je = jend
        END IF
        DO j=jbeg,je
          f4b(j) = f4b(j) + sb(j, k, 4)
          f4vb(j+1) = f4vb(j+1) + 0.5*sb(j, k, 4)
          f4vb(j-1) = f4vb(j-1) - 0.5*sb(j, k, 4)
          f4b(j-1) = f4b(j-1) - sb(j, k, 4)
          f3b(j) = f3b(j) + sb(j, k, 3)
          f3vb(j+1) = f3vb(j+1) + 0.5*sb(j, k, 3)
          f3vb(j-1) = f3vb(j-1) - 0.5*sb(j, k, 3)
          f3b(j-1) = f3b(j-1) - sb(j, k, 3)
          f2b(j) = f2b(j) + sb(j, k, 2)
          f2vb(j+1) = f2vb(j+1) + 0.5*sb(j, k, 2)
          f2vb(j-1) = f2vb(j-1) - 0.5*sb(j, k, 2)
          f2b(j-1) = f2b(j-1) - sb(j, k, 2)
        ENDDO
        CALL POPCONTROL1B(branch)
        IF (branch .NE. 0) THEN
          j = jend
          temp3b15 = 0.5*sb(j, k, 4)
          f4b(j) = f4b(j) + sb(j, k, 4)
          f4vb(j-2) = f4vb(j-2) + temp3b15
          f4vb(j-1) = f4vb(j-1) - 4.*temp3b15
          f4vb(j) = f4vb(j) + 3*temp3b15
          f4b(j-1) = f4b(j-1) - sb(j, k, 4)
          temp3b16 = 0.5*sb(j, k, 3)
          f3b(j) = f3b(j) + sb(j, k, 3)
          f3vb(j-2) = f3vb(j-2) + temp3b16
          f3vb(j-1) = f3vb(j-1) - 4.*temp3b16
          f3vb(j) = f3vb(j) + 3*temp3b16
          f3b(j-1) = f3b(j-1) - sb(j, k, 3)
          temp3b17 = 0.5*sb(j, k, 2)
          f2b(j) = f2b(j) + sb(j, k, 2)
          f2vb(j-2) = f2vb(j-2) + temp3b17
          f2vb(j-1) = f2vb(j-1) - 4.*temp3b17
          f2vb(j) = f2vb(j) + 3*temp3b17
          f2b(j-1) = f2b(j-1) - sb(j, k, 2)
        END IF
        DO j=1,jd-1
          j1 = j + 1
C
          a1 = a1v(j1) + a1v(j)
          a2 = a2v(j1) + a2v(j)
          a5 = a5v(j1) + a5v(j)
          d1 = d1v(j)
          d2 = d2v(j)
          d4 = d4v(j)
          d5 = d5v(j)
          d7 = d7v(j)
C
          ukp1 = q(j, k+1, 2)/q(j, k+1, 1)
          ukm1 = q(j, k-1, 2)/q(j, k-1, 1)
          duk = 0.5*(ukp1-ukm1)
C
          vkp1 = q(j, k+1, 3)/q(j, k+1, 1)
          vkm1 = q(j, k-1, 3)/q(j, k-1, 1)
          dvk = 0.5*(vkp1-vkm1)
C
          ekp1 = q(j, k+1, 4)/q(j, k+1, 1) - .5*(ukp1**2+vkp1**2)
          ekm1 = q(j, k-1, 4)/q(j, k-1, 1) - .5*(ukm1**2+vkm1**2)
          dek = 0.5*(ekp1-ekm1)
C
          t4 = u(j1)*a1v(j1) + u(j)*a1v(j)
          t5 = v(j1)*a2v(j1) + v(j)*a2v(j)
          t6 = u(j1)*a5v(j1) + u(j)*a5v(j)
          t7 = v(j1)*a5v(j1) + v(j)*a5v(j)
          t8 = a4v(j1) + a4v(j)
C
C
          du = u(j1) - u(j)
          dv = v(j1) - v(j)
          dei = e(j1) - e(j)
          d4b = dek*f4vb(j)
          dekb = d4*f4vb(j)
          temp7b3 = 0.5*d7*dvk*f4vb(j)
          temp7b4 = 0.5*(ukp1+ukm1)*f4vb(j)
          d7b = dvk*f2vb(j) + dvk*temp7b4
          dvkb = d2*f3vb(j) + d7*f2vb(j) + d7*temp7b4
          temp7b6 = 0.5*d5*duk*f4vb(j)
          temp7b7 = 0.5*(vkp1+vkm1)*f4vb(j)
          d5b = duk*f3vb(j) + duk*temp7b7
          dukb = d5*f3vb(j) + d1*f2vb(j) + d5*temp7b7
          temp7b8 = 0.5**2*f4vb(j)
          d2b = dvk*f3vb(j) + (vkp1**2-vkm1**2)*temp7b8
          temp7b5 = 0.5**2*f4vb(j)
          d1b = duk*f2vb(j) + (ukp1**2-ukm1**2)*temp7b5
          f4vb(j) = 0.0
          t4b = du*f4b(j)
          t7b = du*f4b(j)
          dub = a5*f3b(j) + a1*f2b(j) + (t4+t7)*f4b(j)
          t5b = dv*f4b(j)
          t6b = dv*f4b(j)
          dvb = a2*f3b(j) + a5*f2b(j) + (t5+t6)*f4b(j)
          t8b = dei*f4b(j)
          deib = t8*f4b(j)
          f4b(j) = 0.0
          f3vb(j) = 0.0
          a5b = dv*f2b(j) + du*f3b(j)
          a2b = dv*f3b(j)
          f3b(j) = 0.0
          f2vb(j) = 0.0
          a1b = du*f2b(j)
          f2b(j) = 0.0
          eb(j1) = eb(j1) + deib
          eb(j) = eb(j) - deib
          vb(j1) = vb(j1) + dvb
          vb(j) = vb(j) - dvb
          ub(j1) = ub(j1) + dub
          ub(j) = ub(j) - dub
          a4vb(j1) = a4vb(j1) + t8b
          a4vb(j) = a4vb(j) + t8b
          vb(j1) = vb(j1) + a5v(j1)*t7b
          a5vb(j1) = a5vb(j1) + v(j1)*t7b
          vb(j) = vb(j) + a5v(j)*t7b
          a5vb(j) = a5vb(j) + v(j)*t7b
          ub(j1) = ub(j1) + a5v(j1)*t6b
          a5vb(j1) = a5vb(j1) + u(j1)*t6b
          ub(j) = ub(j) + a5v(j)*t6b
          a5vb(j) = a5vb(j) + u(j)*t6b
          vb(j1) = vb(j1) + a2v(j1)*t5b
          a2vb(j1) = a2vb(j1) + v(j1)*t5b
          vb(j) = vb(j) + a2v(j)*t5b
          a2vb(j) = a2vb(j) + v(j)*t5b
          ub(j1) = ub(j1) + a1v(j1)*t4b
          a1vb(j1) = a1vb(j1) + u(j1)*t4b
          ub(j) = ub(j) + a1v(j)*t4b
          a1vb(j) = a1vb(j) + u(j)*t4b
          ekp1b = 0.5*dekb
          ukp1b = d1*2*ukp1*temp7b5 + 0.5*dukb - .5*2*ukp1*ekp1b + 
     +      temp7b3
          vkp1b = d2*2*vkp1*temp7b8 + 0.5*dvkb - .5*2*vkp1*ekp1b + 
     +      temp7b6
          ekm1b = -(0.5*dekb)
          ukm1b = temp7b3 - 0.5*dukb - .5*2*ukm1*ekm1b - d1*2*ukm1*
     +      temp7b5
          vkm1b = temp7b6 - 0.5*dvkb - .5*2*vkm1*ekm1b - d2*2*vkm1*
     +      temp7b8
          temp7b9 = ekm1b/q(j, k-1, 1)
          qb(j, k-1, 4) = qb(j, k-1, 4) + temp7b9
          qb(j, k-1, 1) = qb(j, k-1, 1) - q(j, k-1, 4)*temp7b9/q(j, k-1
     +      , 1)
          temp7b10 = ekp1b/q(j, k+1, 1)
          qb(j, k+1, 4) = qb(j, k+1, 4) + temp7b10
          qb(j, k+1, 1) = qb(j, k+1, 1) - q(j, k+1, 4)*temp7b10/q(j, k+1
     +      , 1)
          temp7b11 = vkm1b/q(j, k-1, 1)
          qb(j, k-1, 3) = qb(j, k-1, 3) + temp7b11
          qb(j, k-1, 1) = qb(j, k-1, 1) - q(j, k-1, 3)*temp7b11/q(j, k-1
     +      , 1)
          temp7b12 = vkp1b/q(j, k+1, 1)
          qb(j, k+1, 3) = qb(j, k+1, 3) + temp7b12
          qb(j, k+1, 1) = qb(j, k+1, 1) - q(j, k+1, 3)*temp7b12/q(j, k+1
     +      , 1)
          temp7b13 = ukm1b/q(j, k-1, 1)
          qb(j, k-1, 2) = qb(j, k-1, 2) + temp7b13
          qb(j, k-1, 1) = qb(j, k-1, 1) - q(j, k-1, 2)*temp7b13/q(j, k-1
     +      , 1)
          temp7b14 = ukp1b/q(j, k+1, 1)
          qb(j, k+1, 2) = qb(j, k+1, 2) + temp7b14
          qb(j, k+1, 1) = qb(j, k+1, 1) - q(j, k+1, 2)*temp7b14/q(j, k+1
     +      , 1)
          d7vb(j) = d7vb(j) + d7b
          d5vb(j) = d5vb(j) + d5b
          d4vb(j) = d4vb(j) + d4b
          d2vb(j) = d2vb(j) + d2b
          d1vb(j) = d1vb(j) + d1b
          a5vb(j1) = a5vb(j1) + a5b
          a5vb(j) = a5vb(j) + a5b
          a2vb(j1) = a2vb(j1) + a2b
          a2vb(j) = a2vb(j) + a2b
          a1vb(j1) = a1vb(j1) + a1b
          a1vb(j) = a1vb(j) + a1b
        ENDDO
        DO j=1,jd
          ra = 1./q(j, k, 1)
          u(j) = q(j, k, 2)*ra
          v(j) = q(j, k, 3)*ra
          e(j) = q(j, k, 4)*ra - .5*(u(j)**2+v(j)**2)
          tt = ggm1*e(j)
          vmue = c2bp*tt*SQRT(tt)/(c2b+tt)
          turm = turmu(j, k)
          vnu = vmue + turm
          gkap = vmue + prtr*turm
          rj = 1./q(j, k, nq)
          rkm = 1./q(j, k-1, nq)
          rkp = 1./q(j, k+1, nq)
C
          a4v(j) = (xx(j, k)**2+xy(j, k)**2)*rj
C
          d1v(j) = (4./3.*xx(j, k-1)*yx(j, k-1)+xy(j, k-1)*yy(j, k-1))*
     +      rkm
          d1v(j) = d1v(j) + (4./3.*xx(j, k+1)*yx(j, k+1)+xy(j, k+1)*yy(j
     +      , k+1))*rkp
C
          d2v(j) = (4./3.*xy(j, k-1)*yy(j, k-1)+xx(j, k-1)*yx(j, k-1))*
     +      rkm
          d2v(j) = d2v(j) + (4./3.*xy(j, k+1)*yy(j, k+1)+xx(j, k+1)*yx(j
     +      , k+1))*rkp
C
          d4v(j) = (xy(j, k-1)*yy(j, k-1)+xx(j, k-1)*yx(j, k-1))*rkm
          d4v(j) = d4v(j) + (xy(j, k+1)*yy(j, k+1)+xx(j, k+1)*yx(j, k+1)
     +      )*rkp
C
          d5v(j) = (-(2./3.*xy(j, k-1)*yx(j, k-1))+xx(j, k-1)*yy(j, k-1)
     +      )*rkm
          d5v(j) = d5v(j) + (-(2./3.*xy(j, k+1)*yx(j, k+1))+xx(j, k+1)*
     +      yy(j, k+1))*rkp
C
          d7v(j) = (-(2./3.*xx(j, k-1)*yy(j, k-1))+xy(j, k-1)*yx(j, k-1)
     +      )*rkm
          d7v(j) = d7v(j) + (-(2./3.*xx(j, k+1)*yy(j, k+1))+xy(j, k+1)*
     +      yx(j, k+1))*rkp
          temp5 = xx(j, k)**2
          temp5b = (a4v(j)+temp5*(rj/3.))*a1vb(j)
          temp5b0 = vnu*dre*a1vb(j)
          temp6 = xy(j, k)**2
          temp6b = (a4v(j)+temp6*(rj/3.))*a2vb(j)
          temp6b0 = vnu*dre*a2vb(j)
          temp7b2 = xx(j, k)*xy(j, k)*a5vb(j)
          temp7b = rj*temp7b2/3.
          temp7b0 = gkpr*a4v(j)*a4vb(j)
          temp7b1 = gkpr*d4v(j)*d4vb(j)
          vnub = d5v(j)*dre*d5vb(j) + d1v(j)*dre*d1vb(j) + dre*temp6b + 
     +      dre*temp5b + dre*temp7b + d2v(j)*dre*d2vb(j) + d7v(j)*dre*
     +      d7vb(j)
          dreb = dreb + d5v(j)*vnu*d5vb(j) + d2v(j)*vnu*d2vb(j) + gkap*
     +      temp7b0 + vnu*temp6b + vnu*temp5b + vnu*temp7b + d1v(j)*vnu*
     +      d1vb(j) + gkap*temp7b1 + d7v(j)*vnu*d7vb(j)
          d7vb(j) = vnu*dre*d7vb(j)
          d5vb(j) = vnu*dre*d5vb(j)
          gkapb = dre*temp7b0 + dre*temp7b1
          d4vb(j) = gkpr*gkap*dre*d4vb(j)
          d2vb(j) = vnu*dre*d2vb(j)
          d1vb(j) = vnu*dre*d1vb(j)
          rkpb = (xx(j, k+1)*yy(j, k+1)-xy(j, k+1)*(2./3.)*yx(j, k+1))*
     +      d5vb(j) + (xy(j, k+1)*(4./3.)*yy(j, k+1)+xx(j, k+1)*yx(j, k+
     +      1))*d2vb(j) + (xx(j, k+1)*(4./3.)*yx(j, k+1)+xy(j, k+1)*yy(j
     +      , k+1))*d1vb(j) + (xy(j, k+1)*yy(j, k+1)+xx(j, k+1)*yx(j, k+
     +      1))*d4vb(j) + (xy(j, k+1)*yx(j, k+1)-xx(j, k+1)*(2./3.)*yy(j
     +      , k+1))*d7vb(j)
          rkmb = (xx(j, k-1)*yy(j, k-1)-xy(j, k-1)*(2./3.)*yx(j, k-1))*
     +      d5vb(j) + (xy(j, k-1)*(4./3.)*yy(j, k-1)+xx(j, k-1)*yx(j, k-
     +      1))*d2vb(j) + (xx(j, k-1)*(4./3.)*yx(j, k-1)+xy(j, k-1)*yy(j
     +      , k-1))*d1vb(j) + (xy(j, k-1)*yy(j, k-1)+xx(j, k-1)*yx(j, k-
     +      1))*d4vb(j) + (xy(j, k-1)*yx(j, k-1)-xx(j, k-1)*(2./3.)*yy(j
     +      , k-1))*d7vb(j)
          d7vb(j) = 0.0
          d5vb(j) = 0.0
          d4vb(j) = 0.0
          d2vb(j) = 0.0
          d1vb(j) = 0.0
          a4vb(j) = temp6b0 + temp5b0 + gkpr*gkap*dre*a4vb(j)
          rjb = temp6*temp6b0/3. + (xx(j, k)**2+xy(j, k)**2)*a4vb(j) + 
     +      temp5*temp5b0/3. + vnu*dre*temp7b2/3.
          a5vb(j) = 0.0
          a2vb(j) = 0.0
          a1vb(j) = 0.0
          a4vb(j) = 0.0
          qb(j, k+1, nq) = qb(j, k+1, nq) - rkpb/q(j, k+1, nq)**2
          qb(j, k-1, nq) = qb(j, k-1, nq) - rkmb/q(j, k-1, nq)**2
          qb(j, k, nq) = qb(j, k, nq) - rjb/q(j, k, nq)**2
          vmueb = vnub + gkapb
          turmb = vnub + prtr*gkapb
          turmub(j, k) = turmub(j, k) + turmb
          temp3 = tt/(c2b+tt)
          temp4 = SQRT(tt)
          temp3b18 = temp4*c2bp*vmueb/(c2b+tt)
          IF (tt .EQ. 0.0) THEN
            ttb = (1.0-temp3)*temp3b18
          ELSE
            ttb = (1.0-temp3)*temp3b18 + temp3*c2bp*vmueb/(2.0*temp4)
          END IF
          eb(j) = eb(j) + ggm1*ttb
          qb(j, k, 4) = qb(j, k, 4) + ra*eb(j)
          ub(j) = ub(j) - .5*2*u(j)*eb(j)
          vb(j) = vb(j) - .5*2*v(j)*eb(j)
          rab = q(j, k, 3)*vb(j) + q(j, k, 2)*ub(j) + q(j, k, 4)*eb(j)
          eb(j) = 0.0
          qb(j, k, 3) = qb(j, k, 3) + ra*vb(j)
          vb(j) = 0.0
          qb(j, k, 2) = qb(j, k, 2) + ra*ub(j)
          ub(j) = 0.0
          qb(j, k, 1) = qb(j, k, 1) - rab/q(j, k, 1)**2
        ENDDO
      ENDDO
      b4vb = 0.0
      b1vb = 0.0
      b5vb = 0.0
      b2vb = 0.0
      DO j=jbeg,jend
        DO k=1,kd
          ra = 1./q(j, k, 1)
          u(k) = q(j, k, 2)*ra
          v(k) = q(j, k, 3)*ra
          e(k) = q(j, k, 4)*ra - .5*(u(k)**2+v(k)**2)
          tt = ggm1*e(k)
          vmue = c2bp*tt*SQRT(tt)/(c2b+tt)
          turm = turmu(j, k)
          vnu = vmue + turm
          gkap = vmue + prtr*turm
          rj = 1./q(j, k, nq)
          rjm = 1./q(j-1, k, nq)
          rjp = 1./q(j+1, k, nq)
C
          b4v(k) = (yx(j, k)**2+yy(j, k)**2)*rj
          b1v(k) = (b4v(k)+yx(j, k)**2/3.*rj)*vnu*dre
          b2v(k) = (b4v(k)+yy(j, k)**2/3.*rj)*vnu*dre
          b5v(k) = yx(j, k)*yy(j, k)/3.*rj*vnu*dre
          b4v(k) = b4v(k)*gkpr*gkap*dre
C
          d1v(k) = (4./3.*xx(j-1, k)*yx(j-1, k)+xy(j-1, k)*yy(j-1, k))*
     +      rjm
          d1v(k) = d1v(k) + (4./3.*xx(j+1, k)*yx(j+1, k)+xy(j+1, k)*yy(j
     +      +1, k))*rjp
          d1v(k) = vnu*dre*d1v(k)
C
          d2v(k) = (4./3.*xy(j-1, k)*yy(j-1, k)+xx(j-1, k)*yx(j-1, k))*
     +      rjm
          d2v(k) = d2v(k) + (4./3.*xy(j+1, k)*yy(j+1, k)+xx(j+1, k)*yx(j
     +      +1, k))*rjp
          d2v(k) = vnu*dre*d2v(k)
C
          d4v(k) = (xy(j-1, k)*yy(j-1, k)+xx(j-1, k)*yx(j-1, k))*rjm
          d4v(k) = d4v(k) + (xy(j+1, k)*yy(j+1, k)+xx(j+1, k)*yx(j+1, k)
     +      )*rjp
          d4v(k) = d4v(k)*gkpr*gkap*dre
C
          d5v(k) = (-(2./3.*xy(j-1, k)*yx(j-1, k))+xx(j-1, k)*yy(j-1, k)
     +      )*rjm
          d5v(k) = d5v(k) + (-(2./3.*xy(j+1, k)*yx(j+1, k))+xx(j+1, k)*
     +      yy(j+1, k))*rjp
          d5v(k) = vnu*dre*d5v(k)
C
          d7v(k) = (-(2./3.*xx(j-1, k)*yy(j-1, k))+xy(j-1, k)*yx(j-1, k)
     +      )*rjm
          d7v(k) = d7v(k) + (-(2./3.*xx(j+1, k)*yy(j+1, k))+xy(j+1, k)*
     +      yx(j+1, k))*rjp
          d7v(k) = vnu*dre*d7v(k)
        ENDDO
C
        IF (nhalo .EQ. 1) THEN
          ke = kend - 1
C
          CALL PUSHCONTROL1B(1)
        ELSE
          CALL PUSHCONTROL1B(0)
          IF (nhalo .GT. 1) ke = kend
        END IF
        DO k=kbeg,ke
          f4b(k) = f4b(k) + sb(j, k, 4)
          f4vb(k+1) = f4vb(k+1) + 0.5*sb(j, k, 4)
          f4vb(k-1) = f4vb(k-1) - 0.5*sb(j, k, 4)
          f4b(k-1) = f4b(k-1) - sb(j, k, 4)
          f3b(k) = f3b(k) + sb(j, k, 3)
          f3vb(k+1) = f3vb(k+1) + 0.5*sb(j, k, 3)
          f3vb(k-1) = f3vb(k-1) - 0.5*sb(j, k, 3)
          f3b(k-1) = f3b(k-1) - sb(j, k, 3)
          f2b(k) = f2b(k) + sb(j, k, 2)
          f2vb(k+1) = f2vb(k+1) + 0.5*sb(j, k, 2)
          f2vb(k-1) = f2vb(k-1) - 0.5*sb(j, k, 2)
          f2b(k-1) = f2b(k-1) - sb(j, k, 2)
        ENDDO
        CALL POPCONTROL1B(branch)
        IF (branch .NE. 0) THEN
          k = kend
          tempb = 0.5*sb(j, k, 4)
          f4b(k) = f4b(k) + sb(j, k, 4)
          f4vb(k-2) = f4vb(k-2) + tempb
          f4vb(k-1) = f4vb(k-1) - 4.*tempb
          f4vb(k) = f4vb(k) + 3.*tempb
          f4b(k-1) = f4b(k-1) - sb(j, k, 4)
          tempb0 = 0.5*sb(j, k, 3)
          f3b(k) = f3b(k) + sb(j, k, 3)
          f3vb(k-2) = f3vb(k-2) + tempb0
          f3vb(k-1) = f3vb(k-1) - 4.*tempb0
          f3vb(k) = f3vb(k) + 3*tempb0
          f3b(k-1) = f3b(k-1) - sb(j, k, 3)
          tempb1 = 0.5*sb(j, k, 2)
          f2b(k) = f2b(k) + sb(j, k, 2)
          f2vb(k-2) = f2vb(k-2) + tempb1
          f2vb(k-1) = f2vb(k-1) - 4.*tempb1
          f2vb(k) = f2vb(k) + 3*tempb1
          f2b(k-1) = f2b(k-1) - sb(j, k, 2)
        END IF
        DO k=1,kd-1
          k1 = k + 1
C
          b1 = b1v(k1) + b1v(k)
          b2 = b2v(k1) + b2v(k)
          b5 = b5v(k1) + b5v(k)
          d1 = d1v(k)
          d2 = d2v(k)
          d4 = d4v(k)
          d5 = d5v(k)
          d7 = d7v(k)
          ujp1 = q(j+1, k, 2)/q(j+1, k, 1)
          ujm1 = q(j-1, k, 2)/q(j-1, k, 1)
          duj = 0.5*(ujp1-ujm1)
C
          vjp1 = q(j+1, k, 3)/q(j+1, k, 1)
          vjm1 = q(j-1, k, 3)/q(j-1, k, 1)
          dvj = 0.5*(vjp1-vjm1)
C
          ejp1 = q(j+1, k, 4)/q(j+1, k, 1) - .5*(ujp1**2+vjp1**2)
          ejm1 = q(j-1, k, 4)/q(j-1, k, 1) - .5*(ujm1**2+vjm1**2)
          dej = 0.5*(ejp1-ejm1)
C
          t4 = u(k1)*b1v(k1) + u(k)*b1v(k)
          t5 = v(k1)*b2v(k1) + v(k)*b2v(k)
          t6 = u(k1)*b5v(k1) + u(k)*b5v(k)
          t7 = v(k1)*b5v(k1) + v(k)*b5v(k)
          t8 = b4v(k1) + b4v(k)
C
C
          du = u(k1) - u(k)
          dv = v(k1) - v(k)
          dei = e(k1) - e(k)
          d4b = dej*f4vb(k)
          dejb = d4*f4vb(k)
          temp3b3 = 0.5*d7*duj*f4vb(k)
          temp3b4 = 0.5*(vjp1+vjm1)*f4vb(k)
          d7b = duj*f3vb(k) + duj*temp3b4
          dujb = d7*f3vb(k) + d1*f2vb(k) + d7*temp3b4
          temp3b6 = 0.5*d5*dvj*f4vb(k)
          temp3b7 = 0.5*(ujp1+ujm1)*f4vb(k)
          d5b = dvj*f2vb(k) + dvj*temp3b7
          dvjb = d2*f3vb(k) + d5*f2vb(k) + d5*temp3b7
          temp3b5 = 0.5**2*f4vb(k)
          d2b = dvj*f3vb(k) + (vjp1**2-vjm1**2)*temp3b5
          temp3b8 = 0.5**2*f4vb(k)
          d1b = duj*f2vb(k) + (ujp1**2-ujm1**2)*temp3b8
          f4vb(k) = 0.0
          t4b = du*f4b(k)
          t7b = du*f4b(k)
          dub = b5*f3b(k) + b1*f2b(k) + (t4+t7)*f4b(k)
          t5b = dv*f4b(k)
          t6b = dv*f4b(k)
          dvb = b2*f3b(k) + b5*f2b(k) + (t5+t6)*f4b(k)
          t8b = dei*f4b(k)
          deib = t8*f4b(k)
          f4b(k) = 0.0
          f3vb(k) = 0.0
          b5b = dv*f2b(k) + du*f3b(k)
          b2b = dv*f3b(k)
          f3b(k) = 0.0
          f2vb(k) = 0.0
          b1b = du*f2b(k)
          f2b(k) = 0.0
          eb(k1) = eb(k1) + deib
          eb(k) = eb(k) - deib
          vb(k1) = vb(k1) + dvb
          vb(k) = vb(k) - dvb
          ub(k1) = ub(k1) + dub
          ub(k) = ub(k) - dub
          b4vb(k1) = b4vb(k1) + t8b
          b4vb(k) = b4vb(k) + t8b
          vb(k1) = vb(k1) + b5v(k1)*t7b
          b5vb(k1) = b5vb(k1) + v(k1)*t7b
          vb(k) = vb(k) + b5v(k)*t7b
          b5vb(k) = b5vb(k) + v(k)*t7b
          ub(k1) = ub(k1) + b5v(k1)*t6b
          b5vb(k1) = b5vb(k1) + u(k1)*t6b
          ub(k) = ub(k) + b5v(k)*t6b
          b5vb(k) = b5vb(k) + u(k)*t6b
          vb(k1) = vb(k1) + b2v(k1)*t5b
          b2vb(k1) = b2vb(k1) + v(k1)*t5b
          vb(k) = vb(k) + b2v(k)*t5b
          b2vb(k) = b2vb(k) + v(k)*t5b
          ub(k1) = ub(k1) + b1v(k1)*t4b
          b1vb(k1) = b1vb(k1) + u(k1)*t4b
          ub(k) = ub(k) + b1v(k)*t4b
          b1vb(k) = b1vb(k) + u(k)*t4b
          ejp1b = 0.5*dejb
          vjp1b = d2*2*vjp1*temp3b5 + 0.5*dvjb - .5*2*vjp1*ejp1b + 
     +      temp3b3
          ujp1b = d1*2*ujp1*temp3b8 + 0.5*dujb - .5*2*ujp1*ejp1b + 
     +      temp3b6
          ejm1b = -(0.5*dejb)
          vjm1b = temp3b3 - 0.5*dvjb - .5*2*vjm1*ejm1b - d2*2*vjm1*
     +      temp3b5
          ujm1b = temp3b6 - 0.5*dujb - .5*2*ujm1*ejm1b - d1*2*ujm1*
     +      temp3b8
          temp3b9 = ejm1b/q(j-1, k, 1)
          qb(j-1, k, 4) = qb(j-1, k, 4) + temp3b9
          qb(j-1, k, 1) = qb(j-1, k, 1) - q(j-1, k, 4)*temp3b9/q(j-1, k
     +      , 1)
          temp3b10 = ejp1b/q(j+1, k, 1)
          qb(j+1, k, 4) = qb(j+1, k, 4) + temp3b10
          qb(j+1, k, 1) = qb(j+1, k, 1) - q(j+1, k, 4)*temp3b10/q(j+1, k
     +      , 1)
          temp3b11 = vjm1b/q(j-1, k, 1)
          qb(j-1, k, 3) = qb(j-1, k, 3) + temp3b11
          qb(j-1, k, 1) = qb(j-1, k, 1) - q(j-1, k, 3)*temp3b11/q(j-1, k
     +      , 1)
          temp3b12 = vjp1b/q(j+1, k, 1)
          qb(j+1, k, 3) = qb(j+1, k, 3) + temp3b12
          qb(j+1, k, 1) = qb(j+1, k, 1) - q(j+1, k, 3)*temp3b12/q(j+1, k
     +      , 1)
          temp3b13 = ujm1b/q(j-1, k, 1)
          qb(j-1, k, 2) = qb(j-1, k, 2) + temp3b13
          qb(j-1, k, 1) = qb(j-1, k, 1) - q(j-1, k, 2)*temp3b13/q(j-1, k
     +      , 1)
          temp3b14 = ujp1b/q(j+1, k, 1)
          qb(j+1, k, 2) = qb(j+1, k, 2) + temp3b14
          qb(j+1, k, 1) = qb(j+1, k, 1) - q(j+1, k, 2)*temp3b14/q(j+1, k
     +      , 1)
          d7vb(k) = d7vb(k) + d7b
          d5vb(k) = d5vb(k) + d5b
          d4vb(k) = d4vb(k) + d4b
          d2vb(k) = d2vb(k) + d2b
          d1vb(k) = d1vb(k) + d1b
          b5vb(k1) = b5vb(k1) + b5b
          b5vb(k) = b5vb(k) + b5b
          b2vb(k1) = b2vb(k1) + b2b
          b2vb(k) = b2vb(k) + b2b
          b1vb(k1) = b1vb(k1) + b1b
          b1vb(k) = b1vb(k) + b1b
        ENDDO
        DO k=1,kd
          ra = 1./q(j, k, 1)
          u(k) = q(j, k, 2)*ra
          v(k) = q(j, k, 3)*ra
          e(k) = q(j, k, 4)*ra - .5*(u(k)**2+v(k)**2)
          tt = ggm1*e(k)
          vmue = c2bp*tt*SQRT(tt)/(c2b+tt)
          turm = turmu(j, k)
          vnu = vmue + turm
          gkap = vmue + prtr*turm
          rj = 1./q(j, k, nq)
          rjm = 1./q(j-1, k, nq)
          rjp = 1./q(j+1, k, nq)
C
          b4v(k) = (yx(j, k)**2+yy(j, k)**2)*rj
C
          d1v(k) = (4./3.*xx(j-1, k)*yx(j-1, k)+xy(j-1, k)*yy(j-1, k))*
     +      rjm
          d1v(k) = d1v(k) + (4./3.*xx(j+1, k)*yx(j+1, k)+xy(j+1, k)*yy(j
     +      +1, k))*rjp
C
          d2v(k) = (4./3.*xy(j-1, k)*yy(j-1, k)+xx(j-1, k)*yx(j-1, k))*
     +      rjm
          d2v(k) = d2v(k) + (4./3.*xy(j+1, k)*yy(j+1, k)+xx(j+1, k)*yx(j
     +      +1, k))*rjp
C
          d4v(k) = (xy(j-1, k)*yy(j-1, k)+xx(j-1, k)*yx(j-1, k))*rjm
          d4v(k) = d4v(k) + (xy(j+1, k)*yy(j+1, k)+xx(j+1, k)*yx(j+1, k)
     +      )*rjp
C
          d5v(k) = (-(2./3.*xy(j-1, k)*yx(j-1, k))+xx(j-1, k)*yy(j-1, k)
     +      )*rjm
          d5v(k) = d5v(k) + (-(2./3.*xy(j+1, k)*yx(j+1, k))+xx(j+1, k)*
     +      yy(j+1, k))*rjp
C
          d7v(k) = (-(2./3.*xx(j-1, k)*yy(j-1, k))+xy(j-1, k)*yx(j-1, k)
     +      )*rjm
          d7v(k) = d7v(k) + (-(2./3.*xx(j+1, k)*yy(j+1, k))+xy(j+1, k)*
     +      yx(j+1, k))*rjp
          temp1 = yx(j, k)**2
          temp1b = (b4v(k)+temp1*(rj/3.))*b1vb(k)
          temp1b0 = vnu*dre*b1vb(k)
          temp2 = yy(j, k)**2
          temp2b = (b4v(k)+temp2*(rj/3.))*b2vb(k)
          temp2b0 = vnu*dre*b2vb(k)
          temp3b2 = yx(j, k)*yy(j, k)*b5vb(k)
          temp3b = rj*temp3b2/3.
          temp3b0 = gkpr*b4v(k)*b4vb(k)
          temp3b1 = gkpr*d4v(k)*d4vb(k)
          vnub = d5v(k)*dre*d5vb(k) + d1v(k)*dre*d1vb(k) + dre*temp2b + 
     +      dre*temp1b + dre*temp3b + d2v(k)*dre*d2vb(k) + d7v(k)*dre*
     +      d7vb(k)
          dreb = dreb + d5v(k)*vnu*d5vb(k) + d2v(k)*vnu*d2vb(k) + gkap*
     +      temp3b0 + vnu*temp2b + vnu*temp1b + vnu*temp3b + d1v(k)*vnu*
     +      d1vb(k) + gkap*temp3b1 + d7v(k)*vnu*d7vb(k)
          d7vb(k) = vnu*dre*d7vb(k)
          d5vb(k) = vnu*dre*d5vb(k)
          gkapb = dre*temp3b0 + dre*temp3b1
          d4vb(k) = gkpr*gkap*dre*d4vb(k)
          d2vb(k) = vnu*dre*d2vb(k)
          d1vb(k) = vnu*dre*d1vb(k)
          rjpb = (xx(j+1, k)*yy(j+1, k)-xy(j+1, k)*(2./3.)*yx(j+1, k))*
     +      d5vb(k) + (xy(j+1, k)*(4./3.)*yy(j+1, k)+xx(j+1, k)*yx(j+1, 
     +      k))*d2vb(k) + (xx(j+1, k)*(4./3.)*yx(j+1, k)+xy(j+1, k)*yy(j
     +      +1, k))*d1vb(k) + (xy(j+1, k)*yy(j+1, k)+xx(j+1, k)*yx(j+1, 
     +      k))*d4vb(k) + (xy(j+1, k)*yx(j+1, k)-xx(j+1, k)*(2./3.)*yy(j
     +      +1, k))*d7vb(k)
          rjmb = (xx(j-1, k)*yy(j-1, k)-xy(j-1, k)*(2./3.)*yx(j-1, k))*
     +      d5vb(k) + (xy(j-1, k)*(4./3.)*yy(j-1, k)+xx(j-1, k)*yx(j-1, 
     +      k))*d2vb(k) + (xx(j-1, k)*(4./3.)*yx(j-1, k)+xy(j-1, k)*yy(j
     +      -1, k))*d1vb(k) + (xy(j-1, k)*yy(j-1, k)+xx(j-1, k)*yx(j-1, 
     +      k))*d4vb(k) + (xy(j-1, k)*yx(j-1, k)-xx(j-1, k)*(2./3.)*yy(j
     +      -1, k))*d7vb(k)
          d7vb(k) = 0.0
          d5vb(k) = 0.0
          d4vb(k) = 0.0
          d2vb(k) = 0.0
          d1vb(k) = 0.0
          b4vb(k) = temp2b0 + temp1b0 + gkpr*gkap*dre*b4vb(k)
          rjb = temp2*temp2b0/3. + (yx(j, k)**2+yy(j, k)**2)*b4vb(k) + 
     +      temp1*temp1b0/3. + vnu*dre*temp3b2/3.
          b5vb(k) = 0.0
          b2vb(k) = 0.0
          b1vb(k) = 0.0
          b4vb(k) = 0.0
          qb(j+1, k, nq) = qb(j+1, k, nq) - rjpb/q(j+1, k, nq)**2
          qb(j-1, k, nq) = qb(j-1, k, nq) - rjmb/q(j-1, k, nq)**2
          qb(j, k, nq) = qb(j, k, nq) - rjb/q(j, k, nq)**2
          vmueb = vnub + gkapb
          turmb = vnub + prtr*gkapb
          turmub(j, k) = turmub(j, k) + turmb
          temp = tt/(c2b+tt)
          temp0 = SQRT(tt)
          tempb2 = temp0*c2bp*vmueb/(c2b+tt)
          IF (tt .EQ. 0.0) THEN
            ttb = (1.0-temp)*tempb2
          ELSE
            ttb = (1.0-temp)*tempb2 + temp*c2bp*vmueb/(2.0*temp0)
          END IF
          eb(k) = eb(k) + ggm1*ttb
          qb(j, k, 4) = qb(j, k, 4) + ra*eb(k)
          ub(k) = ub(k) - .5*2*u(k)*eb(k)
          vb(k) = vb(k) - .5*2*v(k)*eb(k)
          rab = q(j, k, 3)*vb(k) + q(j, k, 2)*ub(k) + q(j, k, 4)*eb(k)
          eb(k) = 0.0
          qb(j, k, 3) = qb(j, k, 3) + ra*vb(k)
          vb(k) = 0.0
          qb(j, k, 2) = qb(j, k, 2) + ra*ub(k)
          ub(k) = 0.0
          qb(j, k, 1) = qb(j, k, 1) - rab/q(j, k, 1)**2
        ENDDO
      ENDDO
      reyb = reyb - .5*dreb/rey**2
      END
