C        Generated by TAPENADE     (INRIA, Tropics team)
C  Tapenade 3.6 (r4343) - 10 Feb 2012 10:52
C
C  Differentiation of weno5 in reverse (adjoint) mode:
C   gradient     of useful results: d e weno5 a b c
C   with respect to varying inputs: d e a b c
C*************************************************************************
      SUBROUTINE WENO5_BQ(a, ab, b, bb, c, cb, d, db, e, eb, weno5b)
      IMPLICIT NONE
C*************************************************************************
      REAL weno5
      REAL weno5b
      REAL a, b, c, d, e
      REAL ab, bb, cb, db, eb
      REAL b1, b2, epsw, djm1, ejm1, dj, ej, djp1, ejp1
      REAL djm1b, ejm1b, djb, ejb, djp1b, ejp1b
      REAL dis0, dis1, dis2, q30, q31, q32, d01, d02, a1ba0, a2ba0
      REAL dis0b, dis1b, dis2b, q30b, q31b, q32b, d01b, d02b, a1ba0b, 
     +     a2ba0b
      REAL w0, w1, w2
      REAL w0b, w1b, w2b
      REAL tempb0
      REAL tempb
      b1 = 13./12.
      b2 = 1./6.
      epsw = 1.e-6
      djm1 = a - 2.*b + c
      ejm1 = a - 4.*b + 3.*c
      dj = b - 2.*c + d
      ej = b - d
      djp1 = c - 2.*d + e
      ejp1 = 3.*c - 4.*d + e
      dis0 = b1*djm1*djm1 + 0.25*ejm1*ejm1 + epsw
      dis1 = b1*dj*dj + 0.25*ej*ej + epsw
      dis2 = b1*djp1*djp1 + 0.25*ejp1*ejp1 + epsw
      q30 = 2.*a - 7.*b + 11.*c
      q31 = -b + 5.*c + 2.*d
      q32 = 2.*c + 5.*d - e
      d01 = dis0/dis1
      d02 = dis0/dis2
      a1ba0 = 6.*d01
      a2ba0 = 3.*d02
      w0 = 1./(1.+a1ba0+a2ba0)
      w1 = a1ba0*w0
      w2 = 1. - w0 - w1
      tempb = b2*weno5b
      q30b = w0*tempb
      q31b = w1*tempb
      w2b = q32*tempb
      w1b = q31*tempb - w2b
      w0b = a1ba0*w1b - w2b + q30*tempb
      q32b = w2*tempb
      tempb0 = -(w0b/(a1ba0+a2ba0+1.)**2)
      a1ba0b = tempb0 + w0*w1b
      a2ba0b = tempb0
      d02b = 3.*a2ba0b
      d01b = 6.*a1ba0b
      dis0b = d01b/dis1 + d02b/dis2
      dis2b = -(dis0*d02b/dis2**2)
      dis1b = -(dis0*d01b/dis1**2)
      djp1b = b1*2*djp1*dis2b
      ejp1b = 0.25*2*ejp1*dis2b
      eb = eb + ejp1b + djp1b - q32b
      djb = b1*2*dj*dis1b
      ejb = 0.25*2*ej*dis1b
      db = db + 2.*q31b - 2.*djp1b + djb - ejb - 4.*ejp1b + 5.*q32b
      djm1b = b1*2*djm1*dis0b
      ejm1b = 0.25*2*ejm1*dis0b
      cb = cb + 5.*q31b + 3.*ejp1b - 2.*djb + djm1b + 3.*ejm1b + djp1b +
     +  11.*q30b + 2.*q32b
      bb = bb + djb - 7.*q30b - 2.*djm1b - 4.*ejm1b + ejb - q31b
      ab = ab + ejm1b + djm1b + 2.*q30b
      END
